### ISSUE TITLE
Issue with multi-account

### ISSUE THREAD

**Issue by stom79** [NicolasConstant/sengi#114]
Hey,

I added an account on an instance, but I took the wrong one (a bot). I wanted to reconnect the other one (same instance), but even by deleting the bot account, as soon as I add the new one I can't connect it and it opens the old deleted one.

**Comment by NicolasConstant** [comment]
Oh this is a good one: it's a side-effect of being already logged-in on the instance with the first account, and then being redirected with the old credentials instead of the new one. 
I must check again this workflow to be a little more resilient in this special case. 

In order to be able to login until I fix this, here is how you could reset

If you're using the web version, you could go to your instance and log-out before adding the account again, it's not great, but it will permit you to log-in again to solve the issue. 

If it's the desktop version, well. It's the same thing but a little bit trickier:
- Open DevTools by using Help/Toggle Dev Tools
- Go to the console, enter the following line and hit the enter key:
 `window.location.href = "http://your.instance.url";`
- Log-out
- Close sengi and reopen it to log with your good account


Thanks for testing Sengi! How did you handle this special case in Fedilab?
