### ISSUE TITLE
spell checker

### ISSUE THREAD

**Issue by ghost** [NicolasConstant/sengi#153]
That would be nice to have a spell checker with Sengi. I currently use the version 0.14.0 (deb file).

**Comment by NicolasConstant** [comment]
Just "for information", there is now a way (since I still didn't found a solution for the Electron build) to have a desktop installation AND spell checking: using the PWA. 
You just have to open the sengi web version in a browser that supports PWA installation (firefox don't do it on desktop yet, chrome/chromium does), and install it from there. :) 

Not ideal... but it works. 
It's also not the good icon and so on, I'm waiting a proper icon to update all this. ;)

**Comment by Exagone313** [comment]
Each Electron applications should be able to Chromium's own spell checker. It may not be perfect but it's a good start to complete this feature.

**Comment by NicolasConstant** [comment]
fixed in the last [electron build](https://github.com/NicolasConstant/sengi-electron/releases/tag/v1.6.3).
