### ISSUE TITLE
Cannot use two account on same Mastodon instance

### ISSUE THREAD

**Issue by ahangarha** [NicolasConstant/sengi#282]
The primary reason for me to use Sengi is to run multiple accounts on desktop. I have different accounts on different instances for different purposes. Today I noticed that I cannot login to a new account which is on same instance as another account. If I want to login, it shows me access approval for the other account, preventing me to add new account credentials.

**Comment by NicolasConstant** [comment]
Yes, this is a mastodon limitation: you have to log out from your currently logged-in account and then relog with your second account:

![image](https://user-images.githubusercontent.com/5437247/81615710-0c69aa00-93b0-11ea-8558-f57955afac88.png)

Sometime the log-out doesn't redirect you to Sengi, so you'll have to close the app, reopen it and then add the new account. 

It's not ideal but it's the way it is currently (at least I didn't found a trick for this issue yet).

**Comment by yannicka** [comment]
Is it not possible to isolate accounts with containers/profiles?

**Comment by NicolasConstant** [comment]
I don't thing a website itself can trigger such functionality (for security reasons). And I don't think it's an app responsibility to handle this issue: Mastodon itself should be able to unlog/relog someone and redirect it as requested. 

I will open an issue on this in the Mastodon repo.

**Comment by yannicka** [comment]
On Electron level, maybe something like this: <https://stackoverflow.com/a/55090086>?

But it's a bit of a hack. :sweat_smile:

**Comment by NicolasConstant** [comment]
Yes, if I had an Electron-only build it would do the trick (or something equivalent), the thing is Sengi is also available as a WebApp ; and can also be installed via Chrome/Chromium as a desktop app since it's a PWA too (I personally use this last one). 
So I have the same codebase for everyone and I can't rely on external browser sessions (and even in Electron it would be quite difficult to handle anyway). 

Please keep in mind that you can register multi-accounts from a single instance, it's not like it's not possible (and this would be very problematic if it was the case), you just have to unlog and relog with the good account, and maybe close Sengi in the process, and you'll have all those accounts set in Sengi.
Not ideal of course, but once done you don't need to do it again on the device (since the JWT tokens doesn't expire in Mastodon, and that I renew the Pleroma ones automatically).

**Comment by xanathon** [comment]
I have a Vivaldi setup where I use two separate browser instances with separate user profiles on the same Windows desktop.

So far with every software or account those are separated, if I am logged into Twitter for example in one browser instance, I am not automatically logged in in the other, as it should be. With Mastodon If I open the server url in the second instance I am logged in. I think this is very strange and should not happen. I also see security problems.

**Comment by NicolasConstant** [comment]
> I think this is very strange and should not happen.

What is very strange?

**Comment by NicolasConstant** [comment]
Closing, this is a Mastodon issue and not a Sengi's one.
