### ISSUE TITLE
Flatpak option

### ISSUE THREAD

**Issue by TheEvilSkeleton** [NicolasConstant/sengi#311]
Hello, any plans on making a Flatpak for it and potentially even uploading it to Flathub?

I've heard that Electron is hard to get it flatpak'd, but I know a project that does get it working: [zypak](https://github.com/refi64/zypak)

**Comment by NicolasConstant** [comment]
Hi! 
I would love to provide a flatpak build but I'm currently using electron-builder to build all the current outputs (win/macos/snap/deb/appimage) and unfortunately they are not supporting flatpak yet:
https://github.com/electron-userland/electron-builder/issues/512

But I've seen the [bounty](https://gitpay.me/#/task/352) is still increasing so hopefully we'll have it someday. When it will be available, I'll add flatpak to the supported outputs (and a lot of electron app will also do it, I guess).

**Comment by kallisti5** [comment]
Oh.  I was looking for a nice Mastedon client. This wasn't showing up on Fedora, ArchLinux, or Pop-OS due to the lack of flatpak. Would love to see a flatpak version!

**Comment by koyuawsmbrtn** [comment]
Same, I'm also building desktop applications with Electron and Flatpak support isn't really here yet

**Comment by TheEvilSkeleton** [comment]
@NicolasConstant what are your thoughts on https://github.com/endlessm/electron-installer-flatpak?

**Comment by NicolasConstant** [comment]
Even if some might see it as a "solution" it's not really the case for me. 

I have set a CI/CD pipeline with `electron-builder` to output all binaries (executed on various architectures, publishing automatically the result on Github, etc). When I want to support another type of package, I only have to add a new entry in the electron-builder's config file. Doing it this way makes me maintain only one pipeline (and it is still some work because it breaks time to time) to output all binaries. 

I'm not really happy with the idea to create and maintain a whole other CI/CD pipeline only for a single binary that fulfills the needs that are already covered by AppImage and Snap. 
Or course - and as already stated - if electron-builder supports one day the Flatpak output, I will be more than happy to provide such build. But I don't really have the time right now to set and maintain a whole CI/CD pipeline only to add another linux build in the list. 

I hope I don't sound too rude about this, but that's really the issue with Flatpak not being supported by the "go-to jack-of-all-trade" Electron packager. 😕

**Comment by TheEvilSkeleton** [comment]
You don't sound rude at all. I asked for your thoughts on something and you were clear about your thoughts, I really appreciate it.

I'm new to those stuff, so I didn't know that it was possible to just add an entry and make it work magically.

**Comment by kallisti5** [comment]
electron-builder now supports flatpak:
https://github.com/electron-userland/electron-builder/issues/512

**Comment by NicolasConstant** [comment]
this is a really good news, thanks for the heads up!

**Comment by mtwb47** [comment]
Sorry to bump this old issue, but is there any update on a flatpak version?

**Comment by NicolasConstant** [comment]
I have to find some time to create a new electron build with the latest version, if a flatpak is available at that time, it will be part of the outputs. 🙂

**Comment by dentad** [comment]
Yes, please provide a flatpak alongside your snap! :-D

**Comment by nekohayo** [comment]
If I understand correctly, this is a github UI configuration issue, rather than needing to change some config line somewhere in the codebase/repository, right? (Just checking here if that's something that people here could provide a MR for somehow)

**Comment by koyuawsmbrtn** [comment]
Flathub plans to make a developer web interface similar to Snapcraft and Electron added build support for Flatpaks. If everything seems like I think it will then porting apps like these to Flatpak should be easier than ever. Right now nobody than just a handful of people know how Flatpak works.

**Comment by NicolasConstant** [comment]
@nekohayo it's both: a CICD change + an update of the electron project in the repository. Since the codebase of Sengi and the Electron build are not linked (the Electron build is only behaving like a browser) it's not that much work, but I just need to find some time to do some testing and migrate all this.

With the last version of Electron and its dependencies, a Flatpak build should be trivial.

**Comment by NicolasConstant** [comment]
closing due to rehosting the Electron build in another repository
