### ISSUE TITLE
Ability to add a privacy statement and imprint

### ISSUE THREAD

**Issue by mxmehl** [NicolasConstant/sengi#315]
In Germany, you are required to add a privacy policy and imprint for each website you provide.

Can Sengi somehow add a free field for this kind of information, e.g. in the "about" section in the settings menu? Ideally, this would also be configurable in the docker image :+1: 

Obviously, this only affects the web service, not the standalone desktop app

**Comment by NicolasConstant** [comment]
That's an interesting issue with PWA, Sengi don't store nor get any data from users since it only connect to third-party instances (that do get data and can lead to privacy issues).

But yeah, we maybe don't want to get ourselves in the position of explaining those nuances to nonsavvy guys.

What I could do is add a link in the settings to a basic text file, so that you could edit it in your docker environment; and provide a proper privacy policy statement. 
Would that work for you?

**Comment by mxmehl** [comment]
Yes, that would work, although I'd probably have to link to the common privacy notice anyway.

This only concerns privacy however, but there has to be an "imprint" too. Perhaps you could rename "open privacy statement" to "Imprint & Privacy" or so, and leave the rest to the hosters of the instance?

**Comment by NicolasConstant** [comment]
It's out! 🙂 
You can find how to link your own file in this [documentation](https://github.com/NicolasConstant/sengi/blob/master/DOCKER.md).

**Comment by mxmehl** [comment]
Great, thank you!
