### ISSUE TITLE
Issue with Scicomm.xyz

### ISSUE THREAD

**Issue by Silmathoron** [NicolasConstant/sengi#343]
Hi there,
First of all thanks for the nice software!
I have been using Sengi without problem for some time but I recently started having problems with the instance [scicomm.xyz](https://scicomm.xyz).
Though Sengi seems to fetch timelines and notifications properly, it spits

    Http failure response for https://scicomm.xyz/api/v1/instance: 500 OK

errors whenever I try to write a post and fetch users handles (starting to write @ triggers it).
Of course I see no such problem on scicomm's web interface.
Any idea what may be going wrong? Are there more details logs I can check somewhere?

**EDIT:** I forgot to say that I'm using Sengi 1.0.2 and that I did not try "Clear all local data" because I don't know what I does ^^"
**EDIT 2:** and of course, just for completeness, this issue does not occur with accounts on other instances

**Comment by NicolasConstant** [comment]
Yes this instance has an issue: when you're looking to `https://scicomm.xyz/api/v1/instance` it always fails. You should report this issue to your instance's administrator. 

I'm using this endpoint in various part of the code because I sometime needs info it provide (version and type of software (pleroma/mastodon)) to choose what kind of API/behavior to choose. 
I could look at making the code more robust when this happen by making guesses, but that's won't be the ideal case and it might fail in other part of the code.

**Comment by Silmathoron** [comment]
OK, I'll see with them and report back here

**Comment by Borber** [comment]
> Yes this instance has an issue: when you're looking to `https://scicomm.xyz/api/v1/instance` it always fails. You should report this issue to your instance's administrator.
> 
> I'm using this endpoint in various part of the code because I sometime needs info it provide (version and type of software (pleroma/mastodon)) to choose what kind of API/behavior to choose.
> I could look at making the code more robust when this happen by making guesses, but that won't be the ideal case and it might fail in other part of the code.

I think it suffered the same situation https://wxw.moe/

**Comment by Silmathoron** [comment]
Sorry, I forgot to report back but this was indeed an issue with the instance and there was nothing Sengi could do about it so closing.
Link to solution: https://scicomm.xyz/@quokka/105533210975234490
