### ISSUE TITLE
Bug report: HTML code used in CW's renders on Sengi, but not for users of other clients/views. Possible ACE?

### ISSUE THREAD

**Issue by Novimatrem** [NicolasConstant/sengi#348]
I used some HTML code as a joke in a CW tag on a post I was making, and then discovered that, for example, if I use the HTML bold tag in a CW (content warning/title) it goes bold when posted, but only to other users of Sengi.

This even works for very large image tags, I HOPE IT DOES NOT WORK FOR SCRIPTS.

See the attached screenshot as an example, I hope this is fixed soon.

![image](https://user-images.githubusercontent.com/69379708/105232612-8b7ac900-5b60-11eb-9fb7-15ab25f7f829.png)

**Comment by Novimatrem** [comment]
For clarity the following is all that needs to be done to exploit this problem; 
![image](https://user-images.githubusercontent.com/69379708/105232865-ef04f680-5b60-11eb-8558-5e8cd008da28.png)

1. Make a post that has a CW
2. Make that CW be HTML code
3. Post it.

**Comment by Novimatrem** [comment]
Clarifying further, the standard Mastodon web interface doesn't have this issue. It doesn't even allow HTML to format text, let alone.. this..

I am using Sengi's latest snap version, on Linux Ubuntu 20.04

**Comment by NicolasConstant** [comment]
> I HOPE IT DOES NOT WORK FOR SCRIPTS.
All that Sengi displays is provided by the instance, and therefore sanitized directly from there. 

After a quick look, it's logical that images are displayed since... custom emojis are also HTML image tags and therefore displayed. Maybe I should add some validation to distinct apps images and unwanted image code.

**Comment by Novimatrem** [comment]
It also makes CW's that are intended to be tags, for jokes, invisible.
As long as nothing that is dangerous to the overall layout of the page, or is ACE/XSS, is allowed to happen, then I guess it's fine.
I guess it depends upon the limits of what can be rendered/done from there.

**Comment by NicolasConstant** [comment]
Angular is really strict out-of-the-box and sanitize everything [by default](https://angular.io/guide/security#preventing-cross-site-scripting-xss). I'm using the `[innerHTML]="value"` pattern in rendering the CW as in the [example](https://angular.io/guide/security#sanitization-example) and you can see that (without telling Angular explicitly with the usage of methods like `bypassSecurityTrustHtml`) nothing can be injected. 

It's the beauty of Frameworks: it protects you by default. 

From my testing, I see that Mastodon doesn't sanitize the same content when it's provided as CW and when it's provided as the status' message. It might be a bug since the documentation [state otherwise](https://docs.joinmastodon.org/spec/activitypub/#sanitization).

**Comment by Novimatrem** [comment]
I wonder if *somebody else* posted like, a very large height image as a CW, if it could break timeline usability entirely for past replies for a long distance, does seem like something mastodon web doesn't suffer from.

**Comment by NicolasConstant** [comment]
Yes, I'm not happy with this behavior, I'll will fix it to have the same behavior than MastodonUI. 🙂
Thanks for contributing so Sengi!
