### ISSUE TITLE
Timelines/columns need to have some indicator of associated account

### ISSUE THREAD

**Issue by wakest** [NicolasConstant/sengi#35]
these are from two accounts and there is no way to tell which one is owned by which of my two accounts
<img width="669" alt="screen shot 2019-02-23 at 4 20 00 pm" src="https://user-images.githubusercontent.com/7890201/53292366-f1991e80-3786-11e9-92f0-d6210acfef1f.png">

**Comment by NicolasConstant** [comment]
Yes, I'm still thinking how to handle that better. I have those ideas for the moment: 

- In edit mode, show the account used
- Adding the capability to rename the column (so that it can be personalized) 
- Optionally gives the possibility to display the account in the header (but it will be an opt-in option as I fear it might not be very elegant)

I might implement the first two in a near future, and I'm not totally sure about the third.
If you have other ideas, feel free to share. :)

**Comment by wakest** [comment]
being able to have a custom name for any column seems like a good option to have regardless of this issue and it would help with a few things but I don't quite think that it would solve this issue since the columns would still need a default name and then we still have the issue of not knowing which one belongs to which account. I would say the third option would be the best and there are many ways to solve the elegant issue. having just the user icon next to the globe icon could be a good first step and you could even have it only show on hover. 

this is also an option that I don't think would look too bad and clears up any confusion. would be easy to have it be optional as well.

<img width="658" alt="screen shot 2019-02-23 at 5 22 27 pm" src="https://user-images.githubusercontent.com/7890201/53292903-e39bcb80-378f-11e9-8629-a86d99429b62.png">

**Comment by NicolasConstant** [comment]
I really like it, it would also be a good onboarding aspect for new users to show them that the app is specifically designed to handle this. 

I've centered a bit to see how it would look:
![dkqb0fs2](https://user-images.githubusercontent.com/5437247/53293681-45ffc680-37a6-11e9-8069-cc327d8b352d.jpg)

It could also be an opt-out option (globally and/or per-column) as it could be very useful to newcomers.
