### ISSUE TITLE
use /api/v1/accounts/ instead of the search API for account lookup

### ISSUE THREAD

**Issue by ioistired** [NicolasConstant/sengi#384]
See #383. While opening an account profile in Sengi on Pleroma works (unlike opening a post), it takes a long time, about 15 seconds for me. This is because it's waiting for a fulltext search to time out before returning account results. I tried to fix this to use /api/v1/accounts/:id however, some event handlers(?) received an accountName string instead of a full Account object, so I was not able to make them call /api/v1/accounts/:id instead.

**Comment by NicolasConstant** [comment]
Thanks for contributing to Sengi!

Are you using 2.3.0? Because Pleroma broke the search functionality and it has been a huge issue since. See #360.

The issue here is that Sengi isn't a single user client: it's a real multi-users client (loaded and usable at the same time) and you cannot swap API calls like that. For example if  you're using your `Account_1` to open a status seen in a TL from an `Account_2`, both `Account_1` and `Account_2` being on different instances, you won't have the same IDs referring to the same data. And therefore you could have an error, or even worse: using the wrong data to perform the action (that can be disastrous for boost/fav/etc). 

That's why you have seen some curious validation about what was available on instance X or Y in the code before doing the call. The data you're handling might not come from the instance you're calling.

I agree that there is still an optimization possible that would solve some issues in some cases: in the case of a  `Account_1` to  `Account_1` workflow. But as you saw, I don't provide the good data right now to make this change easily, I have to change and validate all the different levels to pass a more adapted object, and even then, we will only solve one use-case, the others will still be broken; Sengi provide its multi-users magic via the search functionality, and there is no workaround.

**Comment by ioistired** [comment]
Arghh I should have searched the open issues first. Can't Sengi match up the instance ID with the instance it retrieved it from and use that instance to fetch the status?

**Comment by NicolasConstant** [comment]
No unfortunately it can't, because if you want to boost or respond to it, you need the one from the user's instance you're using, not the one that is existing in another instance. 

It's really the more complex part of Sengi, and yeah, I'm very unhappy that Pleroma released this version without rolling it back just after, and didn't fix anything since...

**Comment by ioistired** [comment]
Alright, thanks :(

**Comment by Ashdemai** [comment]
Damn, unfortunate that this is still an unsolved issue.

**Comment by NicolasConstant** [comment]
It's out of my control, to fix 100% of the related functionalities in Sengi, we need the Pleroma team to fix their software and have an API that behave like it should.

**Comment by Ashdemai** [comment]
Yeah, this is what I'm sad about.
