### ISSUE TITLE
Soapbox update makes local timeline and notifications panes unusable

### ISSUE THREAD

**Issue by animegrafmays** [NicolasConstant/sengi#399]
Soapbox recently pushed an update that made use of the reply-to explicit addressing feature and stripping mentions of users from the post contents ([can be seen here](https://poa.st/@graf/posts/AF6l6i75AAYK4wBdq4))

because the @ mentions are removed from the replies, they all appear to be top level posts (in the event of the home timeline) or people speaking directly to the user while replying to someone else entirely (viewing notifications pane)

example
![Screenshot_113](https://user-images.githubusercontent.com/71434691/148318481-6f90c3e6-2050-4b69-82cb-639433aa2577.png)

is it possible for sengi to support this, perhaps with a "replying to" above the post contents?

**Comment by alexgleason** [comment]
It's actually Pleroma that's doing this (since v1.0.0). And other implementations like Hubzilla work this way too.

Mastodon ties text mentions closely with the "to" field in ActivityPub, whereas other implementations might determine the "to" field in other ways.

We support a Twitter-like UI in Soapbox FE (Pleroma) now:

![Screenshot from 2022-01-04 17-30-31](https://user-images.githubusercontent.com/3639540/148414282-0e85980d-5678-49e0-a443-fe808011a05f.png)

The "Replying to..." information comes from `status.mentions`. Even though there are no mentions in the text, Pleroma still returns the whole `to` field in there. So Sengi could support displaying it by relying on `status.mentions` alone.

**Comment by alexgleason** [comment]
I made a very basic implementation of it here: https://github.com/alexgleason/sengi/commit/979438a262e4e1596f82e01d79b3085de9c8cbc3

![Screenshot from 2022-01-06 12-15-37](https://user-images.githubusercontent.com/3639540/148433814-5624bf5e-bb02-4b47-acb2-65fe1792c67d.png)

**Comment by NicolasConstant** [comment]
Thanks for providing some ideas to fix this, but I've decided to just keep the usual pattern everyone uses.
It will be available in next release. 🙂

**Comment by alexgleason** [comment]
Cool. Thanks!
