### ISSUE TITLE
Feature request: Opening links to toots inside the app

### ISSUE THREAD

**Issue by crawlserv** [NicolasConstant/sengi#425]
Not sure hat's possible as they do not seem to follow a unified scheme, but it would be awesome to open linked toots inside the app instead of the browser.

**Comment by NicolasConstant** [comment]
It would be very useful indeed, but unfortunately due to the structure of the Fediverse, it's not really feasible technically: it would require to parse every links, make a call to it to check if it's a Fediverse content (toot, profile, etc) and than rewrite the link to keep it local to the app. 
It would be an ActivityPub spammer really quickly. 😕

Thanks for contributing!
