### ISSUE TITLE
What the actual states ?

### ISSUE THREAD

**Issue by BirdInFire** [NicolasConstant/sengi#444]
What's the state of the dev ?

Paused, Abandonned ?

only ask to see if i bother to help or not.

**Comment by NicolasConstant** [comment]
Hi! 
Neither paused nor abandoned: it's maintained but not in active development currently. 🙂

If you want to help on some issues or other, PR are welcome!

**Comment by joaociocca** [comment]
Sengi has so far been the best experience for Mastodon I've had, being a long time Tweetdeck user... but it lacks some more flexibility. It's sad to hear it's not in active development, but I do understand the level of commitment it would take.
I suck at programming, I tried learning a lot of times, but it's just not my thing - it happens, I have other strengths and that's fine. Here's hoping the community picks this up <3

**Comment by NicolasConstant** [comment]
Not being in active development doesn't mean the project is dead. 🙂 It's just that actually I don't invest the same time/work than when Sengi was missing functionalities I wanted.

I use Sengi everyday, and it fit all my needs, that why when I want to code on my free time I usually work on tools and software I'd like to use but aren't existing yet (and Sengi doesn't belong to this category anymore). But that doesn't mean that time to time I don't go back in Sengi's code to fix a bug / fix something that is bothering me / etc.

If you think that some functionalities are missing, or if you have found bugs, please open an issue. Maybe me or another contributor will pick it up one day depending on their bandwidth and own interest to resolve it. But since it's volunteer work, it's obviously not guaranteed.

If one day my [patreon's donations](https://www.patreon.com/nicolasconstant) permits me to exchange corporate working hours for personal project working hours, I would be more than happy to invest more time on those supported project and more in a "contractor" mindset, since it would be paid by the community. If you don't have the knowledge to contribute directly, becoming a patreon is just as useful. If you don't have money, convincing other people to engage in code contribution or monetary contribution is also just as useful.

With that said, don't refrain from posting new issues, they are useful contributions to the project and highly appreciated. 😉 And in the past many of them became reality, so... who knows?

**Comment by kingsinger** [comment]
Would share joaociocca's opinion above. As a Tweetdeck user, this is the best Masto experience I've had. With that said, I make pretty heavy use of lists and I find the current implementation of adding people to lists a little bit cumbersome. So if you are inspired at some point to do more work on Sengi, perhaps that's an area you might want to look at further. 

Here's my issue, especially right now, as I'm ramping up on Masto and following a lot of people. Unless I'm missing something, the only way I've found to add people to groups is to go into the settings where the groups are, click the pencil icon for the group I want to add somebody to and then do a search for that person and add them. But when I'm adding a bunch of new follows, it's hard to keep all those people in my head from memory. So there's a lot of bouncing back and forth. 

What would be a lot of easier (at least for me) is if there was an option on each follows profile page to add or remove them from groups, then a dialog that pops up and allows the user to choose which groups to add them to.

Here's a little video showing what I'm talking about.  https://1drv.ms/v/s!AivGP-VEl3Kjj_YMPgr5hyDOOtKK5w?e=Zw9Dsg

Anyway, if this option already exists but I haven't found it, let me know. Or if there's some other way of going at this that I don't know, let me know that too. 

Beyond that, thanks so much for making Sengi. In general, it's been a godsend.
