### ISSUE TITLE
Desktop file for Linux AppImage has wrong version

### ISSUE THREAD

**Issue by sid-the-sloth** [NicolasConstant/sengi#568]
The `sengi.desktop` file inside the Linux Appimage version `1.2.0` shows wrong version:

```
[Desktop Entry]
Name=Sengi
Exec=AppRun --no-sandbox %U
Terminal=false
Type=Application
Icon=sengi
StartupWMClass=Sengi
X-AppImage-Version=1.1.5.1112
Comment=A multi-account desktop client for Mastodon and Pleroma
Categories=Network;
```

Should show:
`X-AppImage-Version=1.2.0.nnnn`

**Comment by NicolasConstant** [comment]
Yes it's mostly due to the fact the Electron build is only a browser currently fetching the remote webapp and that I have a broken CICD pipeline currently, so I just reuse the 1.1.5 version (and it's also why I don't update the snap version).

When I'll have the CICD working it will be in sync again.
