### ISSUE TITLE
Sengi not picking max character config : GoToSocial

### ISSUE THREAD

**Issue by anantshri** [NicolasConstant/sengi#576]
For GotoSocial self hosted setup i have kept 5000 as max character limit and it was working just fine till 
https://github.com/NicolasConstant/sengi/commit/22cad9e22dbc459c5ea5a92b4035e06cc409def0 patch was added. 

https://github.com/NicolasConstant/sengi/blob/b00c52ff834c78e462c3711908aea67c25467589/src/app/services/instances-info.service.ts#L22  this line specifically checks if the version number provided is 4 or more. where as gotosocial version numbers are in <1 right now so this makes it fallback to v1 where as gotosocial provides a proper v2 endpoint with right details. https://docs.gotosocial.org/en/latest/api/swagger/

**Comment by NicolasConstant** [comment]
The code is correct: if you have a 4.+ instance it uses a `v2/instance` api object, if not it rollback on `v1/instance`.

But I see that GotoSocial rely on the  `configuration.statuses.max_characters` instead of `max_toot_chars` that pleroma and mastodon forks used. I'll fix that in next release.

If you want to have the proper length before the fix, you can change it on your account panel: 
![image](https://user-images.githubusercontent.com/5437247/235337238-81b39e2b-6ab6-4bb5-97c8-d9462b8d4c2c.png)

**Comment by NicolasConstant** [comment]
Ok I had a second look to it, in fact I already had the good parameter analysis. 

The issue is GoToSocial isn't providing a proper versioning: it's providing it's own one (example: `0.10.0 git-89ee9d5`) instead of a mastodon-compatibility one (like pleroma: `2.7.2 (compatible; Pleroma 2.5.1)`) so while I rely a lot on this version to enable/disable functionalities, I get the wrong answer and it doesn't behave as expected. 

That's something I can't fix on my side: MastodonAPI implementers should display a Mastodon version related to the functionalities they support, not a versioning of their software (at least, not as the first value, like Pleroma).

That's something that should be bring to their attention, since Sengi won't be the only software to rely on this versioning to see what's available and what's not.

**Comment by huggenknubbel** [comment]
For GoToSocial, there is an option to enforce "Mastodon like" versioning. 
But this don't change the issue with the wrong chars.
[i have it enabled here](https://social.knubbel.me/api/v1/instance)

**Comment by NicolasConstant** [comment]
That's weird, can you provide me a testing account on this instance? I will just use it for testing purpose.

You can send me the account info via the official account `@sengi_app@mastodon.social`
