### ISSUE TITLE
second account doesn't auto refresh

### ISSUE THREAD

**Issue by KhensU** [NicolasConstant/sengi#654]
Hi,

I have added a second account but it doesn't auto-refresh.  Only on start or ctrl-R does it update.

**Comment by NicolasConstant** [comment]
What software your account's instance is running?

**Comment by KhensU** [comment]
It is running SkyBridge, a BlueSky to Mastodon bridge.  Are there two different operations to refresh a timelime perhaps?

**Comment by NicolasConstant** [comment]
Oh ok. 

Currently I only support officially Mastodon and Pleroma, even if I already have some custom code to enhance compatibility with other Fediverse softwares. 

Regarding SkyBridge, it seems their MastodonAPI is still lacking, since a lot of other 3rd party clients seems to have issues. So it's more a SkyBridge issue than a Sengi one for now, and they're aware since there is already an [open issue](https://github.com/videah/SkyBridge/issues/34) about Sengi. 

When their MastoAPI becomes more mature and if Sengi still have some issues, feel free to reopen an issue here!
